# name of workflow
name: Helllo

on:
  push:
    branches: [main]


# job is inside the workflow
jobs:

#we have name of runners
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to users
        run: echo "Hello-Dost"

  details:
    runs-on: ubuntu-latest
    
    steps:
     - name: Tell docker and python version
       run: docker --version && python --version
